name: Documentation Check

on: [push, pull_request]

permissions:
  contents: read

jobs:
  docs:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Check README exists
      run: |
        if [ ! -f README.md ]; then
          echo "README.md not found!"
          exit 1
        fi
        echo "README.md found ✓"
        
    - name: Check LICENSE exists
      run: |
        if [ ! -f LICENSE ]; then
          echo "LICENSE file not found!"
          exit 1
        fi
        echo "LICENSE file found ✓"
        
    - name: Validate Circuit Design exists
      run: |
        if [ ! -f CircuitDesign/circuit-diagram.png ]; then
          echo "Circuit diagram not found!"
          exit 1
        fi
        echo "Circuit diagram found ✓"
        
    - name: Check Markdown Links
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        use-quiet-mode: 'yes'
