name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Create Release Archive
      run: |
        zip -r digital-clock-${{ github.ref_name }}.zip DigitalClock/ Dependencies/ CircuitDesign/ README.md LICENSE
        
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Digital Clock ${{ github.ref }}
        body: |
          ## Arduino Digital Clock with Alarm Feature
          
          ### 📁 Contents:
          - `DigitalClock/` - Main Arduino sketch
          - `Dependencies/` - Required libraries (LiquidCrystal I2C)
          - `CircuitDesign/` - Circuit diagram and images
          - `README.md` - Complete documentation
          - `LICENSE` - License information
          
          ### 🚀 Quick Start:
          1. Download and extract the archive
          2. Install the library from `Dependencies/LiquidCrystal_I2C-1.1.3.zip`
          3. Open `DigitalClock/DigitalClock.ino` in Arduino IDE
          4. Upload to your Arduino Uno
          
          ### 🔧 Components Required:
          - Arduino Uno
          - LCD 16x2 I2C
          - Buzzer (5V)
          - Jumper wires
        draft: false
        prerelease: false
